# Generated by Django 3.0 on 2019-12-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=50)),
                ('harga_produk', models.IntegerField()),
                ('deskripsi_produk', models.CharField(max_length=1000)),
                ('img_produk', models.CharField(max_length=1000)),
            ],
        ),
    ]
